plugins:
  git-legal:
    enabled: true
  fixme:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  markdownlint:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - src/test/**
        - app/src/test/**
      minimum_severity: major
